num_oport = "//body[contains(@class,'urBdyStd lsPage lsPage--mouse lsPage--hasmargin')]//tr//tr//tr//tr//tr//tr//tr//tr//tr//tr//tr[1]//td[3]//span[1]//input[1]"  # "input[class='lsField__input urEdf2TxtEnbl urEdf2TxtRadius urBorderBox'][maxlength='10']"
statusEventoSelecao = "/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[2]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[2]/span[1]/span[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[11]/td[3]/span[1]/span[1]"
selecionaOpcaoNula = "/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]"
errLoadPaginaOport = "//strong[contains(text(),'» Comportamento inesperado')]"
sairSeguranca = "//span[@class='button_inner']"
sairSegurancaBttSim = "//div[contains(text(),'Sim')]"
botaoBuscar = "/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[2]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/span[1]/div[1]"
clicaOportunidade = "/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[4]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[1]/div[1]/div[1]/div[1]/span[1]/span[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[2]/a[1]/span[1]"
resumoOportunidade = "/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[4]/div[1]"
downloadOport = "DOWNLOAD_BUTTON"
downloadOportFechar = "CLOSE_BUTTON"
emptyRow = "{2:'EMPTYROW'}"
idNaoEncontrada = """(//a[@lsdata="{0:'N\\xfamero',1:""""""',4:true}"])"""
query = "Query 'Minhas Participações' já aberta em outro modo"
idDigitada = "(//input[@size='10'])[1]"
voltaPainelOport = "Voltar para o Painel de Oportunidades"
relatorioSalaColaboracao = "//span[3]//div[1]"  # xpath
notasAnexos = "//span[contains(text(),'Notas e anexos')]"
abaCabecalho = "//span[contains(text(),'Cabeçalho')]"
abaItens = "//span[contains(text(),'Itens')]"
baixarTodosAnexos = r"""(//div[@lsevents="{Press:[{ResponseData:'delta',ClientAction:'submit'},{}]}"])[5]"""
iconeOculos = "//td[16]//a[1]//img[1]"
iconePergaminho = "//td[18]//a[1]//img[1]"
exportarPropostas = "//div[contains(@class,'lsButton lsTbarBtnStd urInlineMetricTop urNoUserSelect urBtnRadius lsButton--design-standard urBtnStd')]"
voltaPrimeiraTela = "//a[contains(text(),'Voltar para a primeira tela')]"
busca_id = "/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[4]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/span[1]/div[1]/div[1]/div[1]/span[1]/span[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[2]/a[1]/span[1]"
